folio-org/ui-plugin-find-instance

- InstanceSearch/InstanceSearch.js
Allow `PropTypes.node` instead of the more restrictive
`PropTypes.string` for labels that may be passed as `<FormattedMessage>`
objects.
> allow PropTypes.node for labels

- CHANGELOG.md
- package.json
Update `stripes-cli` to `v2.0.0`
https://issues.folio.org/browse/UIPFI-23
> UIPFI-23: Update stripes-cli to v2.0.0

- CHANGELOG.md
- InstanceSearch/FindInstanceContainer.js
https://issues.folio.org/browse/UIPFI-36
It looks like the default search index was different from what is used in `ui-inventory`.  This PR is trying to address it.
> UIPFI-36: Change default search index to align it with the ui-inventory module

- InstanceSearch/InstanceSearch.js
- PluginFindRecord/PluginFindRecord.js
- test/bigtest/interactors/PluginFindInstanceInteractor.js
- test/bigtest/network/config.js
- test/bigtest/tests/find-instance-with-trigger-test.js
https://issues.folio.org/browse/UIPFI-87
The changes in https://issues.folio.org/browse/UIPFI-81 required to refetch the full instance record before returning it to a given module. Unfortunately the `onClose` was executing before the refetch was finalized causing to close the modal without an instance record being returned.
> UIPFI-87: Close modal only after instance record is refetched

- CHANGELOG.md
- Imports/imports/filterConfig.js
- InstanceSearch/FindInstanceContainer.js
`mod-search` is not backwards compatible with `mod-inventory`. Some operators and filter names have changed. This PR makes some adjustments to make sure filters work correctly again.
https://issues.folio.org/browse/UIPFI-88
> UIPFI-88: Adjust filters so they work correctly with mod-search

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- Imports/imports/constants.js
- Imports/imports/filterConfig.js
- Imports/imports/utils.js
- InstanceSearch/FindInstanceContainer.js
- package.json
https://issues.folio.org/browse/UIPFI-92
All queries were mapped to `%{query.query}` by default and non of the search options actually worked.
This PR brings the setup we have in `ui-inventory` to make sure the query templates are used.
> UIPFI-92: Build search query based on templates

- CHANGELOG.md
- InstanceSearch/InstanceSearch.js
- PluginFindRecord/PluginFindRecord.js
Only fetch reference data when the plugin is actually opened.
There are some situations where the plugin instance is used multiple times on the same screen (for example in ui-inventory when multiple child or parent instances are present). This was causing an issue because the reference data was fetched once per each instance.
This PR moved the `DataProvider` around so it's only initialized when the plugin is actually opened.
https://issues.folio.org/browse/UIPFI-95
> UIPFI-95: Only fetch reference data when plugin is opened.

- CHANGELOG.md
- Imports/imports/FilterNavigation/FilterNavigation.js
- Imports/imports/FilterNavigation/FilterNavigation.test.js
- Imports/imports/constants.js
- InstanceSearch/InstanceSearch.js
- PluginFindRecord/PluginFindRecordModal.js
- README.md
- test/jest/__mock__/stripesComponents.mock.js
According to requirements for title-level requests feature, we need this plugin but with only `instances` segment.
We added posibility to pass `config` into plugin, which can contain `availableSections` key, that represent sections to render. All uniq and valid sections from `availableSections` will be rendered. First passed section will set as active on first render. `availableSections` and  `config` is not required props. If nothing will passed, all three tabs will be rendered by default. This way we will not break anything, and no changes needed in other places where plugin used.
The new logic of the `FilterNavigation` component is fully covered by Jest/RTL tests.
Also we added information about new props into `README.md`.
https://issues.folio.org/browse/UIPFI-91
> UIPFI-91: Add posibility to change visible filter fragments

- CHANGELOG.md
- InstanceSearch/FindInstanceContainer.js
Fix search of existing instance when moving holdings records between instances.
Previously, `queryIndex` and `queryValue` were taken from `queryParams` parameter passed to `buildQuery` function. The problem is that values for `queryParams`, according to the Stripes Connect [readme.md](https://github.com/folio-org/stripes-connect/blob/master/doc/api.md#functional-paths-and-parameters), are taken from "UI URL's query parameters". 
My guess is that since it's a modal window and UI URL isn't involved here, we get `{}` as a value. That resulted in default values for `queryIndex` and `queryValue` which is why it didn't search properly by any index except `Keyword` one. 
The solution was to use `props` parameter instead, which "contains redundant copies of much of the rest of the information …
> UIPFI-96 Fix search of existing instance when moving holdings

- CHANGELOG.md
- InstanceSearch/FindInstanceContainer.js
The previous implementation was returning an empty string `''` which did not default to `all` causing issues when the search was performed. 
https://issues.folio.org/browse/UIPFI-99
This PR changes `??` to `||` to make sure `all` is set correctly.
> UIPFI-99: Adjust queryIndex

- CHANGELOG.md
- InstanceSearch/FindInstanceContainer.js
- InstanceSearch/InstanceSearch.js
The segment was previously `undefined` when switching between tabs. This was happening because the state is kept in `useState` instead of the query param. 
Passing it as a prop to `FindInstanceContainer` and referencing it via `props` in `buildQuery` made it work again.
https://issues.folio.org/browse/UIPFI-111
> UIPFI-111: Fix segment when switching between filter tabs

- CHANGELOG.md
- package.json
Some direct-deps should be moved out to dev or peer.
Refs [UIPFI-114](https://issues.folio.org/browse/UIPFI-114)
> UIPFI-114 clean up direct dependencies

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
Update Node.js to v18 in GitHub Actions
[UIPFI-122](https://issues.folio.org/browse/UIPFI-122)
> UIPFI-122 Update Node.js to v18 in GitHub Actions

- .eslintrc
- CHANGELOG.md
- InstanceSearch/InstanceSearch.js
- constants/headers.js
- constants/index.js
- hooks/useInstancesQuery.js
- hooks/useInstancesQuery.test.js
Allow users to select Shared instances. Use correct `tenantId` for different selected Instance records
https://github.com/folio-org/ui-plugin-find-instance/assets/19309423/f07bbf19-d2e9-4550-a6e6-88ba648bcff2
[UIPFI-130](https://issues.folio.org/browse/UIPFI-130)
> UIPFI-130 Allow users to select Shared instances

- CHANGELOG.md
- Imports/imports/InstanceFilters/InstanceFilters.js
- Imports/imports/InstanceFilters/InstanceFilters.test.js
- Imports/imports/SharedFilter/SharedFilter.js
- Imports/imports/TenantIdFilter/TenantIdFilter.js
- Imports/imports/constants.js
- InstanceSearch/FindInstanceContainer.js
- InstanceSearch/FindInstanceContainer.test.js
- InstanceSearch/InstanceSearch.js
- PluginFindRecord/PluginFindRecordModal.js
- test/jest/__mock__/stripesComponents.mock.js
Staff suppress facet - default option "No" selected
Similar approach to Inventory - set default `resources.query` properties and track user interaction with staff suppress filter with session storage flag.
https://github.com/folio-org/ui-plugin-find-instance/assets/19309423/7f8ec6c6-74da-479b-a003-ebeb42b08baf
[UIPFI-133](https://folio-org.atlassian.net/browse/UIPFI-133)
> UIPFI-133 Staff suppress facet - default option "No" selected

- PluginFindRecord/PluginFindRecordModal.js
Don't combine current state and next state when `changeType` is `reset.all`. Next state has default values and should be applied without change
https://github.com/folio-org/ui-plugin-find-instance/assets/19309423/2ed1b058-5ccb-4b75-baa1-48511174de40
[UIPFI-133](https://folio-org.atlassian.net/browse/UIPFI-133)
> UIPFI-133 use nextState in queryStateReducer when changeType is reset.all (follow-up)

- CHANGELOG.md
- InstanceSearch/FindInstanceContainer.js
- InstanceSearch/FindInstanceContainer.test.js
- PluginFindRecord/PluginFindRecordModal.js
- PluginFindRecord/PluginFindRecordModal.test.js
The plugin previously stored `qindex` in internal state which was not cleared when clicking "Reset all".
We don't need this separate state because `SearchAndSortQuery` already handles all other state parameters and it makes sense to delegate handling of `qindex` to it too
https://github.com/folio-org/ui-plugin-find-instance/assets/19309423/13491711-abd6-40e3-a94f-8b17f4013594
[UIPFI-147](https://folio-org.atlassian.net/browse/UIPFI-147)
> UIPFI-147 Use `SearchAndSortQuery` `qindex` instead of what is stored in state.

- CHANGELOG.md
- Imports/imports/DataProvider.js
- Imports/imports/HoldingsFilters/HoldingsRecordFilters.test.js
- Imports/imports/InstanceFilters/InstanceFilters.test.js
- Imports/imports/ItemFilters/ItemFilters.test.js
- Imports/imports/LocationFilter/LocationFilter.js
- Imports/imports/LocationFilter/LocationFilter.test.js
- InstanceSearch/FindInstanceContainer.js
- hooks/useLocationsForTenants/useLocationsForTenants.js
- hooks/useLocationsForTenants/useLocationsForTenants.test.js
- test/jest/__mock__/stripesCore.mock.js
Use consolidated locations endpoint to fetch all locations when in central tenant context.
Renamed `_tenantId` when getting locations per tenant to `tenantId` because in consolidated endpoint we get that dat automatically with that property name.
https://github.com/folio-org/ui-plugin-find-instance/assets/19309423/49470236-b5c0-4a9f-a4bc-ccb7dbd49401
[UIPFI-146](https://folio-org.atlassian.net/browse/UIPFI-146)
> UIPFI-146 Use consolidated locations endpoint to fetch all locations when in central tenant context.

- CHANGELOG.md
- src/components/FindInstanceContainer/FindInstanceContainer.js
- src/components/FindInstanceContainer/FindInstanceContainer.test.js
When the request URL exceeds the limit:
1. Show an error toast message;
2. Show a specific error message inside the results list.
Export `buildRecordsManifest` to have one source of truth for ui-inventory and ui-plugin-find-instance.
Use `withSearchErrors` to show the error toast message, it also provides the `isRequestUrlExceededLimit` property for displaying correct error message in results pane.
The tests will pass once the related PRs are merged.
[UIPFI-158](https://folio-org.atlassian.net/browse/UIPFI-158)
https://github.com/folio-org/stripes-inventory-components/pull/61
https://github.com/folio-org/stripes-smart-components/pull/1496
https://github.com/user-attachments/assets/6a60bced-cbc3-4d86-b78e-efe99428f664
> UIPFI-158: Use `withSearchErrors` HOC and `buildRecordsManifest` to display an error when the request URL is exceeded.

- CHANGELOG.md
- src/components/FilterNavigation/FilterNavigation.js
- src/components/FilterNavigation/FilterNavigation.test.js
Be able to see facet options after clicking on the current search segment tab (Instance/Holdings/Item) and then opening the facet.
If a user clicks a current search segment or search mode, do nothing.
Tests will pass after the related PR is merged.
https://github.com/folio-org/stripes-inventory-components/pull/67
[UIPFI-159](https://folio-org.atlassian.net/browse/UIPFI-159)
https://github.com/user-attachments/assets/711d6c25-2763-4f8d-8408-1fc77d21a6b6
- Do JIRAs exist to update …
> UIPFI-159: Prevent `onChange` from being triggered when clicking on the current search segment tab.

- CHANGELOG.md
- src/components/FindInstanceContainer/FindInstanceContainer.js
- src/components/PluginFindRecord/PluginFindRecordModal.js
- src/components/PluginFindRecord/PluginFindRecordModal.test.js
- src/constants/constants.js
Add a sort indicator next to the sortable search headers of search results.
Add `showSortIndicator` to MCL, this will add a sort indicator for all headings.
Add `nonInteractiveHeaders` to remove a sort indicator from the non-interactive headers.
[UIPFI-160](https://folio-org.atlassian.net/browse/UIPFI-160)
Ideally all of the PRs involved in breaking …
> UIPFI-160: Add a sort indicator next to the sortable search headers of search results.

- CHANGELOG.md
- src/FindInstance.js
- src/components/FindInstanceContainer/FindInstanceContainer.js
- src/components/FindInstanceContainer/FindInstanceContainer.test.js
- src/components/PluginFindRecord/PluginFindRecordModal.test.js
- src/constants/constants.js
- test/jest/__mock__/stripesInventoryComponents.mock.js
- translations/ui-plugin-find-instance/en.json
Add Date column to Inventory results list.
https://github.com/folio-org/stripes-inventory-components/pull/71
[UIPFI-162](https://folio-org.atlassian.net/browse/UIPFI-162)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> UIPFI-162: Add Date column to Inventory results list.

- CHANGELOG.md
- src/FindInstance.js
- src/components/PluginFindRecord/PluginFindRecordModal.js
- src/components/PluginFindRecord/PluginFindRecordModal.test.js
Date filters: Clear dates after pressing the reset search button even if values are invalid.
https://github.com/folio-org/stripes-smart-components/pull/1527
https://github.com/folio-org/stripes-inventory-components/pull/83
Use `ResetProvider` to publish the reset event and subscribe to it in filters.
[UIIN-3093](https://folio-org.atlassian.net/browse/UIIN-3093)
https://github.com/user-attachments/assets/ca890dd9-6021-431c-8dc9-bee7946d1293
> UIPFI-164: Use `ResetProvider` to subscribe and publish the reset event and unsubscribe from it after a segment switch.

- CHANGELOG.md
- src/components/PluginFindRecord/PluginFindRecordModal.js
mod-search only allows sorting by actual Instance fields
since 'relevance' is not a real field using it causes a BE error. If a default sort is 'relevance' we need to use an empty string, which is treated as relevance sort on BE side
https://github.com/user-attachments/assets/687d05cc-b34a-4bff-9d29-ba97bd198707
[UIPFI-169](https://folio-org.atlassian.net/browse/UIPFI-169)
> UIPFI-169 Use an empty string as a default sort parameter when Display Settings has `relevance` as a default sort.

- CHANGELOG.md
- package.json
migrate stripes deps and react-intl to sunflower versions
[UIPFI-174](https://folio-org.atlassian.net/browse/UIPFI-174)
[UIPFI-175](https://folio-org.atlassian.net/browse/UIPFI-175)
> migrate stripes deps and react-intl to sunflower versions
