- InstanceSearch/InstanceSearchModal.js
- package.json
Part two of https://github.com/folio-org/ui-inventory/pull/300
> Update inventory UI path

- translations/ui-plugin-find-instance/ca.json
- translations/ui-plugin-find-instance/fr_FR.json
- translations/ui-plugin-find-instance/hu.json
> Update translation strings as of 20181004T193841

- CHANGELOG.md
- InstanceSearch/InstanceSearch.js
- InstanceSearch/InstanceSearchModal.js
- package.json
Uses new `@folio/stripes` package.
> Use stripes 1.0

- translations/ui-plugin-find-instance/ar.json
> Update translation strings as of 20181031T224505

- translations/ui-plugin-find-instance/ar.json
> Update translation strings as of 20181112T151205

- translations/ui-plugin-find-instance/pt_PT.json
> Update translation strings as of 20181212T135930

- translations/ui-plugin-find-instance/en_SE.json
> Update translation strings as of 20190110T173959

- InstanceSearch/InstanceSearch.js
The title attribute should not be use for accessibility.
Refs [STCOM-296](https://issues.folio.org/browse/STCOM-296)
> don't use the title attribute for html elements

- translations/ui-plugin-find-instance/es_419.json
> Update translation strings as of 20190422T163602

- translations/ui-plugin-find-instance/ar.json
- translations/ui-plugin-find-instance/ca.json
- translations/ui-plugin-find-instance/da.json
- translations/ui-plugin-find-instance/de.json
- translations/ui-plugin-find-instance/en_GB.json
- translations/ui-plugin-find-instance/en_SE.json
- translations/ui-plugin-find-instance/en_US.json
- translations/ui-plugin-find-instance/es.json
- translations/ui-plugin-find-instance/es_419.json
- translations/ui-plugin-find-instance/es_ES.json
- translations/ui-plugin-find-instance/fr.json
- translations/ui-plugin-find-instance/fr_FR.json
- translations/ui-plugin-find-instance/hu.json
- translations/ui-plugin-find-instance/it_IT.json
- translations/ui-plugin-find-instance/pt_BR.json
- translations/ui-plugin-find-instance/pt_PT.json
- translations/ui-plugin-find-instance/zh_CN.json
> Update translation strings as of 20190909T193700

- translations/ui-plugin-find-instance/ar.json
> Update translation strings as of 20190918T144452

- translations/ui-plugin-find-instance/it_IT.json
> Update translation strings as of 20190919T124724

- translations/ui-plugin-find-instance/es_ES.json
> Update translation strings as of 20190925T125755

- translations/ui-plugin-find-instance/ru.json
- translations/ui-plugin-find-instance/zh_TW.json
> Update translation strings as of 20191014T135140

- translations/ui-plugin-find-instance/ja.json
> Update translation strings as of 20191028T205642

- translations/ui-plugin-find-instance/he.json
> Update translation strings as of 20191113T214202

- translations/ui-plugin-find-instance/fr_FR.json
> Update translation strings as of 20191122T140350

- translations/ui-plugin-find-instance/fr_FR.json
> Update translation strings as of 20191202T021928

- translations/ui-plugin-find-instance/fr_FR.json
> Update translation strings as of 20191209T142332

- translations/ui-plugin-find-instance/es.json
- translations/ui-plugin-find-instance/es_419.json
> Update translation strings as of 20191220T210632

- translations/ui-plugin-find-instance/it_IT.json
> Update translation strings as of 20200202T214053

- .gitignore
- CHANGELOG.md
- Jenkinsfile
- package.json
- test/bigtest/.eslintrc
- test/bigtest/helpers/PluginHarness.js
- test/bigtest/helpers/PluginHarnessMultiselect.js
- test/bigtest/helpers/helpers.js
- test/bigtest/index.js
- test/bigtest/interactors/ButtonInteractor.js
- test/bigtest/interactors/PluginFindInstanceInteractor.js
- test/bigtest/network/boot.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/instance.js
- test/bigtest/network/index.js
- test/bigtest/network/models/instance.js
- test/bigtest/network/serializers/instance.js
- test/bigtest/tests/find-instance-multiselect-test.js
- test/bigtest/tests/find-instance-test.js
https://issues.folio.org/browse/UIPFI-2
> UIPFI-2 add bigtest

- translations/ui-plugin-find-instance/ur.json
> Update translation strings as of 20200210T220102

- translations/ui-plugin-find-instance/ja.json
> Update translation strings as of 20200413T183215

- translations/ui-plugin-find-instance/zh_TW.json
> Update translation strings as of 20200505T210535

- CHANGELOG.md
- package.json
Updating `react-intl` to `^4.5.1`
https://issues.folio.org/browse/STRIPES-672
> STRIPES-672: Update react-intl version

- test/bigtest/interactors/PluginFindInstanceInteractor.js
Fix tests broken by MCL refactoring
https://issues.folio.org/browse/UIPFI-12
> UIPFI-12 - fix tests broken by MCL refactoring

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIPFI-14
> UIPFI-14: Update stripes to v5, react-router to v5.2

- translations/ui-plugin-find-instance/hi_IN.json
- translations/ui-plugin-find-instance/ko.json
> Update translation strings as of 20200921T192032

- translations/ui-plugin-find-instance/pl.json
> Update translation strings as of 20200924T211627

- CHANGELOG.md
- InstanceSearch/FindInstanceContainer.js
https://issues.folio.org/browse/UIPFI-17
> UIPFI-17: Do not show results without performing a query

- translations/ui-plugin-find-instance/ber.json
> Update translation strings as of 20201109T135508

- .gitignore
- CHANGELOG.md
- Update the .gitignore file
https://issues.folio.org/browse/UIPFI-25
> UIPFI-25: Update the .gitignore file

- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
- Add pull request template
https://issues.folio.org/browse/UIPFI-26
We add the same changes that  was added in scope  https://github.com/folio-org/ui-checkin/pull/409 with only one different in file PULL_REQUEST_TEMPLATE.md we change from UICHKIN-233 to UIPFI-26
> UIPFI-26: Add pull request template

- PluginFindRecord/PluginFindRecordModal.js
https://issues.folio.org/browse/UIPFI-19
Addendum: Add a fix for index labels not being translated.
> UIPFI-19: Fix search index translations

- CHANGELOG.md
- PluginFindRecord/Filters.js
- PluginFindRecord/PluginFindRecord.test.js
- PluginFindRecord/PluginFindRecordModal.js
- PluginFindRecord/PluginFindRecordModal.test.js
- test/jest/__mock__/index.js
- test/jest/__mock__/stripesComponents.mock.js
- test/jest/__mock__/stripesSmartComponents.mock.js
Add tests for directory `PluginFindRecord`
https://issues.folio.org/browse/UIPFI-28
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While …
> UIPFI-28: Add Jest/RTL tests

- InstanceSearch/FindInstanceContainer.js
- test/bigtest/tests/find-instance-multiselect-test.js
After switching to ElasicSearch (mod-search) `publication` field is not present. This PR is trying to address it.
https://issues.folio.org/browse/UIPFI-88
> UIPFI-88 - Fix instance list for instances without publication

- CHANGELOG.md
- InstanceSearch/FindInstanceContainer.js
- PluginFindRecord/PluginFindRecordModal.js
Find an instance - Apply Previous/Next Pagination
Existing code uses fetchMore method to fetch next chunk of records. Hence, offset is incremented on every call.
Hence, in this implementation, fetchmore is conditionally called.
for example-
- on initial search, 100 records are fetched - record range would be 1-100
- on clicking next button (on pagination row), next 100 records are also fetched, which makes the total records fetched as 200 and the offset used in last GET call is 100, record range would be 101-200
- for instance, now previous button (on pagination row) is clicked, MCLRenderer now renders with record range 1-100 which is picked from already fetched records.
- if next button is clicked, MCLRenderer renders with record range 101 - 200, which are again picked from already …
> UIPFI-107 - Find an instance - Apply Previous/Next Pagination

- CHANGELOG.md
- package.json
- test/jest/fixtures/instances.js
https://issues.folio.org/browse/UIPFI-112
Bump search interface to 1.0 to support new API changes.
> UIPFI-112: Bump search interface to 1.0

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIPFI-113
> UIPFI-113: Bump stripes to 8.0.0 for Orchid/2023-R1

- CHANGELOG.md
https://issues.folio.org/browse/UIPFI-115
> Release v6.4.0

- CHANGELOG.md
- Imports/imports/filterConfig.js
https://issues.folio.org/browse/UIPFI-117
> UIPFI-117: Remove callNumber index. Add eye readable and normalized indexes on call numbers

- Imports/imports/ItemFilters/ItemFilters.test.js
- test/jest/__mock__/stripesComponents.mock.js
- test/jest/__mock__/stripesSmartComponents.mock.js
Create Jest/RTL test for ItemFilters.js
Refs: [UIPFI-39](https://issues.folio.org/browse/UIPFI-39)
> UIPFI-39 Create Jest/RTL test for ItemFilters.js

- Imports/imports/HoldingsFilters/HoldingsRecordFilters.test.js
UIPFI-45 create JEST/RTL test cases for HoldingsRecordFilters.js
URL: https://issues.folio.org/browse/UIPFI-45
> UIPFI-45 create JEST/RTL test cases for HoldingsRecordFilters.js

- Imports/imports/InstanceFilters/InstanceFilters.test.js
UIPFI-68 create JEST/RTL test cases for InstanceFilters.js
URL: https://issues.folio.org/browse/UIPFI-68
> UIPFI-68 create JEST/RTL test cases for InstanceFilters.js

- Imports/FilterRenderers/ItemFilters/itemFilterRenderer.test.js
UIPFI-66 JEST/RTL test cases for itemFilterRender.js
URL: https://issues.folio.org/browse/UIPFI-66
> UIPFI-66 JEST/RTL test cases for itemFilterRender.js

- InstanceSearch/FindInstanceContainer.test.js
- test/jest/__mock__/stripesCore.mock.js
- test/jest/__mock__/stripesSmartComponents.mock.js
Create Jest/RTL test for FindInstanceContainer.js
Refs: [UIPFI-52](https://issues.folio.org/browse/UIPFI-52)
> UIPFI-52: create Jest/RTL test for FindInstanceContainer.js

- Imports/imports/utils.test.js
UIPFI-63 JEST/RTL test cases for utils.js
URL: https://issues.folio.org/browse/UIPFI-63
> UIPFI-63 JEST/RTL test cases for utils.js

- InstanceSearch/InstanceSearch.test.js
Create Jest/RTL test for InstanceSearch.js
Refs: [UIPFI-49](https://issues.folio.org/browse/UIPFI-49)
> UIPFI-49 create Jest/RTL test for InstanceSearch.js

- Imports/FilterRenderers/InstanceFilters/instanceFilterRenderer.test.js
Refs:
UIPFI-48 create Jest/RTL test for instanceFilterRenderer.js
URL: https://issues.folio.org/browse/UIPFI-48
> UIPFI-48 create Jest/RTL test for instanceFilterRenderer.js

- Imports/FilterRenderers/HoldingsFilters/holdingsRecordFilterRenderer.test.js
Refs:
create Jest/RTL test for holdingsRecordFilterRenderer.js
URL: https://issues.folio.org/browse/UIPFI-46
> UIPFI-46  create Jest/RTL test for holdingsRecordFilterRenderer.js

- InstanceSearch/FindInstanceContainer.css
- InstanceSearch/FindInstanceContainer.js
Improve shared icon positioning
[UIPFI-123](https://issues.folio.org/browse/UIPFI-123)
> UIPFI-123 Improve shared icon positioning

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- Imports/FilterRenderers/InstanceFilters/instanceFilterRenderer.js
- Imports/imports/HoldingsFilters/HoldingsRecordFilters.js
- Imports/imports/HoldingsFilters/HoldingsRecordFilters.test.js
- Imports/imports/InstanceFilters/InstanceFilters.js
- Imports/imports/InstanceFilters/InstanceFilters.test.js
- Imports/imports/ItemFilters/ItemFilters.js
- Imports/imports/ItemFilters/ItemFilters.test.js
- Imports/imports/SharedFilter/SharedFilter.js
- Imports/imports/SharedFilter/SharedFilter.test.js
- Imports/imports/SharedFilter/index.js
- Imports/imports/filterConfig.js
- test/jest/__mock__/currencyData.mock.js
- test/jest/__mock__/index.js
- test/jest/__mock__/stripesCore.mock.js
- test/jest/helpers/harness.js
- test/jest/helpers/intl.js
Update plugin filters to include Shared Facet
https://github.com/folio-org/ui-plugin-find-instance/assets/19309423/bdd5f844-5cfe-4e25-83b9-2c7afb2802e5
[UIPFI-119](https://issues.folio.org/browse/UIPFI-119)
> UIPFI-119 Update plugin filters to include Shared Facet

- Imports/imports/SharedFilter/SharedFilter.js
Make Shared filter closed by default
[UIPFI-119](https://issues.folio.org/browse/UIPFI-119)
> UIPFI-119 Make Shared filter closed by default

- CHANGELOG.md
- Imports/imports/HoldingsFilters/HoldingsRecordFilters.js
- Imports/imports/InstanceFilters/InstanceFilters.js
- Imports/imports/ItemFilters/ItemFilters.js
- Imports/imports/TenantIdFilter/TenantIdFilter.js
- Imports/imports/TenantIdFilter/TenantIdFilter.test.js
- Imports/imports/TenantIdFilter/index.js
- Imports/imports/filterConfig.js
- temp/useTenantKy/index.js
- temp/useTenantKy/useTenantKy.js
- temp/useTenantKy/useTenantKy.test.js
Add Held By filter.
[UIPFI-125](https://issues.folio.org/browse/UIPFI-125)
https://github.com/folio-org/ui-plugin-find-instance/assets/77053927/8a629086-1b32-43bf-aeb1-ec2a7ce51cc7
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> UIPFI-125: Add Held By filter.

- Imports/imports/HoldingsFilters/HoldingsRecordFilters.js
- Imports/imports/InstanceFilters/InstanceFilters.js
- Imports/imports/ItemFilters/ItemFilters.js
- InstanceSearch/utils.js
- test/jest/__mock__/stripesCore.mock.js
Show `Held By` filter for all consortia tenants.
[UIPFI-125](https://issues.folio.org/browse/UIPFI-125)
https://github.com/folio-org/ui-plugin-find-instance/assets/77053927/75c004ef-4add-4d59-ba6b-d0e6b462ddd5
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
> UIPFI-125: Show Held by filter for all consortia tenants.

- Imports/imports/CheckboxFacet/CheckboxFacet.js
- Imports/imports/CheckboxFacet/CheckboxFacet.test.js
- Imports/imports/CheckboxFacet/CheckboxFacetList.css
- Imports/imports/CheckboxFacet/CheckboxFacetList.js
- Imports/imports/CheckboxFacet/CheckboxFacetList.test.js
- Imports/imports/CheckboxFacet/index.js
- Imports/imports/InstanceFilters/InstanceFilters.test.js
- Imports/imports/TenantIdFilter/TenantIdFilter.js
- Imports/imports/constants.js
- Imports/imports/utils.js
- test/jest/__mock__/stripesComponents.mock.js
Add input field to HeldBy filter.
Copied the `CheckboxFacet` component from `Inventory`, but this version is a bit changed - `facetsStore` (`zustand`) is not applied, internal state is used here.
[UIPFI-125](https://issues.folio.org/browse/UIPFI-125)
https://github.com/folio-org/ui-plugin-find-instance/assets/77053927/86043da3-2526-4abd-932f-ed19a74b6e4e …
> UIPFI-125: Add input field to HeldBy filter.

- CHANGELOG.md
- package.json
Remove eslint deps that are already listed in eslint-config-stripes
[UIPFI-124](https://issues.folio.org/browse/UIPFI-124)
> UIPFI-124 Remove eslint deps that are already listed in eslint-config-stripes

- CHANGELOG.md
- InstanceSearch/InstanceSearch.js
- InstanceSearch/InstanceSearch.test.js
- hooks/useInstancesQuery.js
- hooks/useInstancesQuery.test.js
- test/jest/__mock__/stripesCore.mock.js
- translations/ui-plugin-find-instance/en.json
- utils/index.js
- utils/parseHttpError.js
- utils/parseHttpError.test.js
When trying to link a shared instance to a local instance (child/parent) from a member tenant having a central tenant without permission for viewing instances, the page crashes because the central tenant does not have permission to view (fetch) instances.
- Fetch selected instances from `mod-search` instead of `mod-inventory-storage` module, it allows us to get shared instances in the context of member tenant, there is no need to grant view perms to central tenant just to link instances in member tenant.
https://issues.folio.org/browse/UIPFI-131
If there are breaking changes, please **STOP** and …
> UIPFI-131: Fetch instances from mod-search instead of mod-inventory-storage

- CHANGELOG.md
- Imports/imports/DataProvider.js
- Imports/imports/utils.js
- constants/index.js
- hooks/index.js
- hooks/useLocationsForTenants/index.js
- hooks/useLocationsForTenants/useLocationsForTenants.js
- hooks/useLocationsForTenants/useLocationsForTenants.test.js
Show locations from other tenants in Effective location facet.
[UIPFI-136](https://issues.folio.org/browse/UIPFI-136)
https://github.com/folio-org/ui-plugin-find-instance/assets/77053927/aa5b7257-17d0-48fb-9ea5-95a4fd152698
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> UIPFI-136: ECS Effective location facet is not showing other member tenants.

- Imports/FilterRenderers/InstanceFilters/instanceFilterRenderer.js
- Imports/imports/DataProvider.js
- Imports/imports/InstanceFilters/InstanceFilters.js
Fix plugin opening on non-consortia envs.
Don't wait for the locations to load for each tenant, because it takes too long. Display the loading of the Effective Locations facet until all locations are loaded.
[UIPFI-136](https://issues.folio.org/browse/UIPFI-136)
consortia env:
https://github.com/folio-org/ui-plugin-find-instance/assets/77053927/e4be3eea-ac31-475c-a5e2-3045a1751a10
snapshot env:
https://github.com/folio-org/ui-plugin-find-instance/assets/77053927/eada39da-6ee2-4779-a4ff-776f866e79a1
- What other modules will …
> UIPFI-136: Fix plugin opening on non-consortia envs.

- CHANGELOG.md
- package.json
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> UIPFI-139: Release 7.0.3

- CHANGELOG.md
- Imports/imports/filterConfig.js
- translations/ui-plugin-find-instance/en.json
Add a new search option for instances called `LCCN normalization`.
[UIPFI-135](https://folio-org.atlassian.net/browse/UIPFI-135)
https://github.com/folio-org/ui-plugin-find-instance/assets/77053927/e096315d-e0e9-4707-a1ab-86342b6f1120
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> UIPFI-135: Add a new search option for instances called LCCN normalization.

- PluginFindRecord/PluginFindRecordModal.js
Fix next filter state calculation. More details in related PR in stripes-smart-components - https://github.com/folio-org/stripes-smart-components/pull/1458
https://github.com/folio-org/ui-plugin-find-instance/assets/19309423/31ab1e9e-fcf0-43be-ba6c-35cded2336b0
[UIPFI-133](https://folio-org.atlassian.net/browse/UIPFI-133)
> UIPFI-133 Fix next filter state calculation (follow-up)

- CHANGELOG.md
- Imports/imports/filterConfig.js
- translations/ui-plugin-find-instance/en.json
Add a new Instance search option `Classification, normalize` for the `Instance` toggle.
[UIPFI-149](https://folio-org.atlassian.net/browse/UIPFI-149)
https://github.com/folio-org/ui-plugin-find-instance/assets/77053927/663cc38a-03c3-4463-8e7a-54c261218fce
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking …
> UIPFI-149: Add new Instance search option 'Classification, normalize' for the 'Instance' toggle.

- CHANGELOG.md
- src/FindInstance.js
- src/FindInstance.test.js
- src/components/FindInstanceContainer/FindInstanceContainer.js
- src/components/PluginFindRecord/PluginFindRecord.js
- src/contexts/DataProvider/DataProvider.js
- src/hooks/useInstancesQuery/useInstancesQuery.js
[UIPFI-157](https://folio-org.atlassian.net/browse/UIPFI-157): ECS - Accept `tenantId` prop to search entries in the specified tenant
There is a corresponding ticket for supporting filters and search https://github.com/folio-org/stripes-inventory-components/pull/66
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
> UIPFI-157: ECS - Accept `tenantId` prop to search entries in the specified tenant

- src/FindInstance.js
UIPFI-157: fix failing query build due to tenantID is undefined and add fallback `tenantId` for the plugin
https://github.com/user-attachments/assets/129be5f4-a20a-4642-80b8-5d4c163d8f18
https://github.com/user-attachments/assets/685dfcbb-3429-4117-8003-588cb3822dfe
https://github.com/user-attachments/assets/56477612-b33e-4dc3-8a1e-3790d950b5ad
Ideally all …
> UIPFI-157: fix failing query build due to tenantID is undefined and add fallback `tenantId` for the plugin

- CHANGELOG.md
- src/components/PluginFindRecord/PluginFindRecordModal.js
Add a label to search input
[UIPFI-142](https://folio-org.atlassian.net/browse/UIPFI-142)
> UIPFI-142 Add a label to search input

- CHANGELOG.md
- src/FindInstance.js
- src/components/FilterNavigation/FilterNavigation.js
React v19: refactor away from default props for functional components.
[UIPFI-150](https://folio-org.atlassian.net/browse/UIPFI-150)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> UIPFI-150: React v19: refactor away from default props for functional components.

- CHANGELOG.md
- package.json
- src/FindInstance.js
- src/components/FindInstanceContainer/FindInstanceContainer.js
- src/components/FindInstanceContainer/FindInstanceContainer.test.js
- src/components/PluginFindRecord/PluginFindRecordModal.js
- src/components/PluginFindRecord/PluginFindRecordModal.test.js
Remove default Staff suppress facet settings
https://github.com/user-attachments/assets/7ba87a1d-51b2-4953-8c62-2946898c4ea6
https://github.com/folio-org/stripes-inventory-components/pull/120
[UIPFI-178](https://folio-org.atlassian.net/browse/UIPFI-178)
> UIPFI-178 Find instance plugin: Remove default Staff suppress facet settings
